Naive Bayes
------

Naive Bayes Algorithm is an supervised classification algorithm 

It works on Bayes theorem of probability to predict the class of unknown data set.

There are three types of Naive Bayes model under scikit learn library :

Gaussian , Multinomial & Bernoulli

In [7]:
import sklearn.naive_bayes
print(dir(sklearn.naive_bayes))

['ABCMeta', 'BaseDiscreteNB', 'BaseEstimator', 'BaseNB', 'BernoulliNB', 'ClassifierMixin', 'ComplementNB', 'GaussianNB', 'LabelBinarizer', 'MultinomialNB', '_ALPHA_MIN', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_check_partial_fit_first_call', 'abstractmethod', 'binarize', 'check_X_y', 'check_array', 'check_consistent_length', 'check_is_fitted', 'issparse', 'label_binarize', 'logsumexp', 'np', 'safe_sparse_dot', 'six', 'warnings']


Gaussian NB
------

A Gaussian Naive Bayes algorithm is a special type of NB algorithm. It’s specifically used when the features have continuous values. It’s also assumed that all the features are following a gaussian distribution i.e, normal distribution.

In [8]:
from sklearn.datasets import load_iris

In [9]:
iris = load_iris() 

In [11]:
print(dir(iris))

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']


In [12]:
print(iris.feature_names) # input columns 

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
print(iris.target_names) # output column has 3 classes  

['setosa' 'versicolor' 'virginica']


In [10]:
X = iris.data 
y = iris.target 

In [14]:
type(X)

numpy.ndarray

In [15]:
type(y)

numpy.ndarray

In [17]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [18]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [19]:
X.shape

(150, 4)

In [20]:
y.shape

(150,)

In [21]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [23]:
X_train.shape

(105, 4)

In [24]:
X_test.shape

(45, 4)

In [25]:
y_train.shape

(105,)

In [26]:
y_test.shape

(45,)

GaussianNB
-------



testing and training 

p(xtrain/ytrain) --- known 

p(xtest/ytest) --- ?

p(xtest/ytest) = (p(xtrain/ytrain) * p(ytrain))/p(xtrain)

In [22]:
from sklearn.naive_bayes import GaussianNB

In [27]:
gnbclf = GaussianNB() 
gnbclf.fit(X_train, y_train) 

GaussianNB(priors=None, var_smoothing=1e-09)

In [28]:
y_pred = gnbclf.predict(X_test)

In [29]:
y_pred

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [30]:
y_test

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [31]:
from sklearn import metrics

print(metrics.accuracy_score(y_test, y_pred)*100)


95.55555555555556


Multinomial NB 
------

Multinomial naive Bayes works similar to Gaussian naive Bayes, however the features are assumed to be multinomially distributed. In practice, this means that this classifier is commonly used when we have discrete data (e.g. movie ratings ranging 1 and 5)

In [2]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
text_data = np.array(['I love python.','venolearn is best','AI is niche skill','AI is trend','AI uses python'])

In [8]:
type(text_data)


numpy.ndarray

In [9]:
count = CountVectorizer()

In [10]:
print(dir(count))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_char_ngrams', '_char_wb_ngrams', '_check_stop_words_consistency', '_check_vocabulary', '_count_vocab', '_get_param_names', '_limit_features', '_sort_features', '_validate_params', '_validate_vocabulary', '_white_spaces', '_word_ngrams', 'analyzer', 'binary', 'build_analyzer', 'build_preprocessor', 'build_tokenizer', 'decode', 'decode_error', 'dtype', 'encoding', 'fit', 'fit_transform', 'get_feature_names', 'get_params', 'get_stop_words', 'input', 'inverse_transform', 'lowercase', 'max_df', 'max_features', 'min_df', 'ngram_range', 'preprocessor', 'set_params', 'stop_words', 'strip_accents', 'token_pattern', 'tokeni

In [11]:
bag_of_words = count.fit_transform(text_data)

In [12]:
type(bag_of_words)

scipy.sparse.csr.csr_matrix

In [13]:
print(bag_of_words)

  (0, 5)	1
  (0, 3)	1
  (1, 1)	1
  (1, 2)	1
  (1, 9)	1
  (2, 6)	1
  (2, 4)	1
  (2, 0)	1
  (2, 2)	1
  (3, 7)	1
  (3, 0)	1
  (3, 2)	1
  (4, 8)	1
  (4, 0)	1
  (4, 5)	1


In [14]:
X = bag_of_words.toarray()

In [17]:
X.shape

(5, 10)

In [37]:
count.get_feature_names()

['ai',
 'best',
 'is',
 'love',
 'niche',
 'python',
 'skill',
 'trend',
 'uses',
 'venolearn']

In [38]:
X

array([[0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 0]], dtype=int64)

In [19]:
y = np.array([0, 1, 2, 3, 4])

In [20]:
mulNBclf = MultinomialNB()

In [21]:
model = mulNBclf.fit(X, y)

In [33]:
test_data = [[1, 0, 1, 0, 1, 0, 1, 0, 0, 0]]
model.predict(test_data)

array([2])

In [34]:
# this problem consists of 5 classes 