Array Vs List
----------------------

Used for storing the data , and are mutable , can be indexed , sliced  and iterated through 

Array can store homogenuos data elements but list stores heterogenuos data elements 

Arrays are specially optimised for arithmetic computations 

Arrays are efficient (functionality and speed)

Arrays are compact (in size)

Below the divison on list and array by certain number

In [2]:
import numpy
array_a = numpy.array([2, 4, 6, 8, 10])
list_a = [3, 6, 9, 12, 15]
print(array_a/2)
print(list_a/3)

[1. 2. 3. 4. 5.]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [4]:
print("________________________________________________")
array_x = numpy.array([1 , 2,  3,  'venolearn'])
print("Checking the type of elements of array")
print(array_x)
print(type(array_x))
for i in array_x:
    print(i)
    print(type(i))
print("________________________________________________")
# output shows the str as type , so in an array all elements are of same type


________________________________________________
Checking the type of elements of array
['1' '2' '3' 'venolearn']
<class 'numpy.ndarray'>
1
<class 'numpy.str_'>
2
<class 'numpy.str_'>
3
<class 'numpy.str_'>
venolearn
<class 'numpy.str_'>
________________________________________________


In [6]:
print("________________________________________________")
list_x = [1 , 2,  3,  'venolearn']
print("Checking the type of elements of list")
print(list_x)
print(type(list_x))
for i in list_x:
    print(i)
    print(type(i))
print("________________________________________________")
# output shows the int & str as type , so in an list all elements are of different type

________________________________________________
Checking the type of elements of list
[1, 2, 3, 'venolearn']
<class 'list'>
1
<class 'int'>
2
<class 'int'>
3
<class 'int'>
venolearn
<class 'str'>
________________________________________________


Numpy
--------

Numpy stands for Numerical Python , 
Numpy is a Library in python that deals with multidimensional Arrays.

In [1]:
import numpy as np 
print(np.__version__)
print(dir(np))

1.15.4
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolut

1 - D Array 
---------

1-D array can be initialised in 2 ways one is with list and other is with arange function 

In [15]:
x = np.array([1, 2, 3, 4, 5, 6])
print(type(x))
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
1
(6,)
6
int32


In [18]:
p = np.arange(10) # arange(stop)
q = np.arange(7,15) # arange(start,stop)
r = np.arange(20,30,2) # arange(start,stop,step)
print(p)
print(type(p))
print(q)
print(type(q))
print(r)
print(type(r))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
[20 22 24 26 28]
<class 'numpy.ndarray'>


In [30]:
p = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9])
print(p)
print(np.mean(p))
print(np.sum(p))
print(np.min(p))
print(np.max(p))
print(np.argmin(p))
print(np.argmax(p))
print(np.std(p))
print(np.median(p))
print(np.percentile(p , 25)) # lower percentile 
print(np.percentile(p , 75)) # upper percentile
print("***********")
from scipy import stats
print(stats.mode(p))

[0 1 2 3 4 5 6 7 8 9 9]
4.909090909090909
54
0
9
0
9
3.0287874998104876
5.0
2.5
7.5
***********
ModeResult(mode=array([9]), count=array([2]))


2-D array
-----------

In [38]:
m = np.array([[1, 2, 3],[4, 5, 6]]) # intialization using list of lists
print(m)
print(m.ndim)
print(m.size)
print(m.shape)

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)


In [41]:
n1 = np.random.random(size=(2,3)) # intialization using random values
print(n1)
print("___________________________________")
n2 = np.random.normal(size=(2,3))
print(n2)
print("___________________________________")
n3 = np.random.randn(2,3)
print(n3)

[[0.09746322 0.08738092 0.46610105]
 [0.77748641 0.06577644 0.43418171]]
___________________________________
[[ 0.04374467 -0.30739924 -1.07912045]
 [-1.85363501 -0.46682485 -0.69578792]]
___________________________________
[[-0.2433834   0.27409395  0.30841211]
 [-0.80104429  0.64599633 -0.49204476]]


In [43]:
k = np.random.randint(low=3,high=6,size=(4,4)) # intialization using random values
print(k)

[[3 4 5 4]
 [5 3 3 4]
 [5 3 5 5]
 [3 3 5 5]]


In [48]:
z = np.zeros(shape=(3,3)) # zeros matrix
print(z)
print("__________________________")
o = np.ones(shape=(3,3)) # ones matrix
print(o)
print("______________________________")
i = np.identity(3) # identity matrix
print(i)
print("_______________________________")
print(np.diagonal(i)) # finding diagonal elements of matrix
print("_______________________")
print(np.trace(i)) # trace of matrix = sum of all diagonal elements
print("______________________")


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
__________________________
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
______________________________
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
_______________________________
[1. 1. 1.]
_______________________
3.0


In [58]:
matrix_a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("_________________________")
print(matrix_a)
print("_________________________")
print(np.linalg.matrix_rank(matrix_a))
print("_________________________")
print(np.linalg.inv(matrix_a))
print("_________________________")
print(np.transpose(matrix_a))
print("_________________________")
print(matrix_a.size)
print(matrix_a.shape)
print(matrix_a.flatten())

_________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
_________________________
2
_________________________
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
_________________________
[[1 4 7]
 [2 5 8]
 [3 6 9]]
_________________________
9
(3, 3)
[1 2 3 4 5 6 7 8 9]


In [2]:
np.full((3,4),1.2345678) # creates a matrix with predefined values 

array([[1.2345678, 1.2345678, 1.2345678, 1.2345678],
       [1.2345678, 1.2345678, 1.2345678, 1.2345678],
       [1.2345678, 1.2345678, 1.2345678, 1.2345678]])

In [5]:
np.linspace(0, 1, 4) # create an array of even space between the given range of values o and 1 

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [10]:
x1 = np.random.randint(20, size=6) #one dimension
x2 = np.random.randint(5, size=(3,4)) #two dimension
print(x1)
print("___________________________________")
print(x2)


[18  1  9  1  6  0]
___________________________________
[[0 0 4 2]
 [1 2 2 4]
 [3 3 0 1]]


Array Indexing
---------

In [41]:
venolearn_array  = np.array([20, 30 , 40 , 50 , 32, 45, 65, 76])
print(venolearn_array)
print(venolearn_array[0])
print(venolearn_array[5])
print(venolearn_array[-1]) # gives the last value 76
print(venolearn_array[-2]) # gives the second last value 65
print(venolearn_array[::-1]) # reverses the entire array elements 
print(np.sort(venolearn_array)) # sorts the entire array in ascending order 
print("_______________________________________________")
venolearn_ndim = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(venolearn_ndim)
print(venolearn_ndim[2,2])
print(venolearn_ndim[1,2])
print(venolearn_ndim[1,1])
print(venolearn_ndim[2,-1])
print(venolearn_ndim[2,-2])
venolearn_ndim[0,0] = 10 # replace value at 0,0 index 
print(venolearn_ndim)

[20 30 40 50 32 45 65 76]
20
45
76
65
[76 65 45 32 50 40 30 20]
[20 30 32 40 45 50 65 76]
_______________________________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
6
5
9
8
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


Array Slicing
-------

In [22]:
print(venolearn_array[2:6]) # gives elements from index 2 to index 5

[40 50 32 45]


In [23]:
print(venolearn_array[:6]) # gives elements from index 0 to index 5

[20 30 40 50 32 45]


In [25]:
print(venolearn_array[2:]) # gives elements from index 2 to index 7

[40 50 32 45 65 76]


In [26]:
print(venolearn_array[::2]) # gives elements at even places

[20 40 32 65]


In [27]:
print(venolearn_array[::1]) # prints the same array

[20 30 40 50 32 45 65 76]


In [31]:
print(venolearn_array[0::2]) # return the elements step by 2

[20 40 32 65]


Array concatenation
-------------

In [43]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])
v = np.concatenate([v1, v2, v3])
print(v)

[1 2 3 4 5 6 7 8 9]


In [50]:
v11 = np.array([[1,2,3],[4,5,6]])
v22 = np.array([[11,22,33],[44,55,66]])
print(np.concatenate([v11, v22])) 
print("___________________________________")
print(np.concatenate([v11, v22],axis=1))     # axis =1 means columns 
print("____________________________________")
print(np.concatenate([v11, v22],axis=0))     # axis =0 means rows 

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]
___________________________________
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]
____________________________________
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]


In [8]:
# concatenation can be used to combine arrays of equal dimension 
x11 = np.array([[1,2,3],[4,5,6]])
print(x11)
print("______________________")
y11 = np.array([[10, 11, 12],[20, 30 , 40 ]])
print(y11)
print("___________________________")
z11 = np.hstack([x11, y11])
print(z11)
x22 = np.array([[9],[9]])
print(x22)
print("__________________________")
z22 = np.hstack([x11, x22])
print(z22)
print("________________________")
z33 = np.vstack([x11, y11])
print(z33)
x33 = np.array([9, 9, 9])
print("____________________________")
z44 = np.vstack([x11, x33])
print(z44)

[[1 2 3]
 [4 5 6]]
______________________
[[10 11 12]
 [20 30 40]]
___________________________
[[ 1  2  3 10 11 12]
 [ 4  5  6 20 30 40]]
[[9]
 [9]]
__________________________
[[1 2 3 9]
 [4 5 6 9]]
________________________
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [20 30 40]]
____________________________
[[1 2 3]
 [4 5 6]
 [9 9 9]]


Broadcasting and matrix operations
----------------------------------

In [9]:
abc = np.array([[1,2,3],[4,5,6]])
print(abc)
print("___________________")
pqr = np.array([[10,20,30],[40,50,60]])
print(pqr)
print("____________________________")
print(abc + pqr)
print("__________________")
print(abc * pqr)
print("_________________")
print(abc - pqr)
print("___________________")
print(abc/pqr)
print("_________________________")

[[1 2 3]
 [4 5 6]]
___________________
[[10 20 30]
 [40 50 60]]
____________________________
[[11 22 33]
 [44 55 66]]
__________________
[[ 10  40  90]
 [160 250 360]]
_________________
[[ -9 -18 -27]
 [-36 -45 -54]]
___________________
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
_________________________


In [15]:
abc = np.array([[1,2,3],[4,5,6],[7, 8, 9]])
v1 = np.array([1, 2, 3])
v2 = np.array([10, 20, 30])
print(np.dot(v1, v2)) # vector vector dot product
print("______________________________________")
print(np.dot(abc, v1)) # matrix vector dot product
print("______________________________________")
print(np.dot(abc, abc)) # matrix matrix dot product
print("______________________________________")
print(np.outer(v1, v2)) # vector vector outer product

140
______________________________________
[14 32 50]
______________________________________
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
______________________________________
[[10 20 30]
 [20 40 60]
 [30 60 90]]


Matrix splitting
--------

In [18]:
x = np.arange(10)
print(x)
x1,x2,x3 = np.split(x,[3,6])
print(x1)
print(x2)
print(x3)
abc = np.array([[1,2,3],[4,5,6],[7, 8, 9],[10, 11, 22]])
print(abc)
print("_______________________________________")
print(np.hsplit(abc,[2,4] )) # Hsplit row count remains same 
print("_______________________________________")
print(np.vsplit(abc,[2,4])) # vsplit column count remains same 

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[3 4 5]
[6 7 8 9]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 22]]
_______________________________________
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3],
       [ 6],
       [ 9],
       [22]]), array([], shape=(4, 0), dtype=int32)]
_______________________________________
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 22]]), array([], shape=(0, 3), dtype=int32)]
